server:
  port: 8080

app:
  kafka:
    bootstrap-servers: localhost:29092
    topic: campaign-commands
    event-topic: campaign-events
    adgroup-topic: adgroup-commands
    adgroup-event-topic: adgroup-events

spring:
  kafka:
    bootstrap-servers: ${app.kafka.bootstrap-servers}
  application:
    name: service-bff
