server:
  port: 8081

app:
  kafka:
    bootstrap-servers: localhost:29092
    topic: demo-messages
    campaign-topic: campaign-commands
    campaign-event-topic: campaign-events
    adgroup-topic: adgroup-commands
    adgroup-event-topic: adgroup-events

spring:
  application:
    name: service-a
